version: "3.9"

services:
  frontend:
    build:
      context: ./to-do
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: production

  backend:
    build:
      context: ./taskflow-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
